# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojos',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo',
        ),
        migrations.AddField(
            model_name='ninjas',
            name='dojo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_apps.Dojos'),
            preserve_default=False,
        ),
    ]
